services:

  docker-registry:

    # main
    image: ${DOCKER_REGISTRY_TAG}
    hostname: ${DOCKER_REGISTRY_HOSTNAME:-docker-registry}
    environment:
      TZ:                            "${TZ}"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/etc/docker/registry/certs/docker-registry.crt"
      REGISTRY_HTTP_TLS_KEY:         "/etc/docker/registry/certs/docker-registry.key"
      REGISTRY_AUTH:                 "htpasswd"
      REGISTRY_AUTH_HTPASSWD_PATH:   "/etc/docker/registry/auth/htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM:  "Registry Realm"
    ports:
      - "${DOCKER_REGISTRY_PORT:-5000}:5000"
    volumes:
      - docker_registry:/var/lib/registry
      - docker_registry_certs:/etc/docker/registry/certs

    # swarm
    configs:
      - source: docker_registry_conf
        target: /etc/docker/registry/config.yml
    secrets:
      - source: docker_registry_htpasswd
        target: /etc/docker/registry/auth/htpasswd
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${DOCKER_REGISTRY_NODE}"

# main
volumes:
  docker_registry:
    external: true
    name: ${DOCKER_VOL_REGISTRY:-docker_registry}
  docker_registry_certs:
    external: true
    name: ${DOCKER_VOL_CERTS:-docker_registry_certs}

# swarm
configs:
  docker_registry_conf:
    external: true
secrets:
  docker_registry_htpasswd:
    external: true