services:

  gitlab:

    # main
    image: "${GITLAB_TAG}"
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      TZ:                    "${TZ}"
      GITLAB_HOSTNAME:       "${GITLAB_HOSTNAME}"
      GITLAB_SSH_PORT:       "${GITLAB_SSH_PORT}"
      GITLAB_EMAIL:          "${GITLAB_EMAIL}"
    ports:
      - "${GITLAB_SSH_PORT}:22"
      - "${GITLAB_HTTPS_PORT}:443"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab

    # swarm
    configs:
      - source: gitlab_conf
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
      - source: gitlab_key
        target: /etc/gitlab/ssl/gitlab.key
      - source: gitlab_crt
        target: /etc/gitlab/ssl/gitlab.crt

  gitlab-runner:

    # main
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
      - gitlab-runner-temp:/home/gitlab-runner

    # swarm
    deploy:
      mode: replicated
      replicas: 1

# main
volumes:
  gitlab_data:
    external: true
  gitlab_logs:
    external: true
  gitlab_config:
    external: true
  gitlab-runner-config:
    external: true
  gitlab-runner-temp:

# swarm
configs:
  gitlab_conf:
    external: true

secrets:
  gitlab_root_password:
    external: true
  gitlab_key:
    external: true
  gitlab_crt:
    external: true
