services:

  oc_crserver:

    # compose
    container_name: 'oc_crserver'
    restart: always

    # main
    image: "${OC_CRSERVER_TAG}"
    hostname: "${OC_CRSERVER_HOSTNAME}"
    command: crserver
    environment:
      OC_CRSERVER_LOCATION: ${OC_CRSERVER_LOCATION}
      OC_CRSERVER_HOSTNAME: ${OC_CRSERVER_HOSTNAME}
    ports:
      - "${OC_CRSERVER_PORT}:1542"
      - "${OC_CRSERVER_HTTP_PORT}:80"
    volumes:
      - oc_crserver:/home/usr1cv8/crserver

# main
volumes:
  oc_crserver:
    name: "${OC_CRSERVER_VOL}"
    external: true