services:

  oc_crserver:

    # main
    image: "${OC_CRSERVER_TAG}"
    hostname: "${OC_CRSERVER_HOSTNAME}"
    command: crserver
    environment:
      OC_CRSERVER_LOCATION: ${OC_CRSERVER_LOCATION}
      OC_CRSERVER_HOSTNAME: ${OC_CRSERVER_HOSTNAME}
    ports:
      - "${OC_CRSERVER_PORT}:1542"
      - "${OC_CRSERVER_HTTP_PORT}:80"

    volumes:
      - oc_crserver:/home/usr1cv8/crserver
    # swarm
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${OC_CRSERVER_NODE}"

# main
volumes:
  oc_crserver:
    name: "${OC_CRSERVER_VOL}"
    external: true