services:

  oc_crserver:

    # main
    image: "${OC_CRSERVER_TAG}"
    hostname: "${OC_CRSERVER_HOSTNAME}"
    command: crserver
    ports:
      - "${OC_CRSERVER_PORT}:1542"
      - "${OC_CRSERVER_HTTP_PORT}:80"

    volumes:
      - "${OC_CRSERVER_VOL}:/home/usr1cv8/crserver"

    # swarm
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${OC_CRSERVER_NODE}"

# main
volumes:
  "${OC_CRSERVER_VOL}":
    external: true