services:

  plantuml:

    # main part
    image: ${PLANTUML_TAG}
    hostname: 'plantuml'
    environment:
      BASE_URL: ${PLANTUML_URL}
    ports:
      - "${PLANTUML_PORT}:8080"
    volumes:
      - plantuml_temp:/tmp/jetty

    # swarm part
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${PLANTUML_NODE}"

  draw-io:

    # main part
    image: ${DRAWIO_TAG}
    hostname: 'drawio'
    environment:
      PUBLIC_DNS: ${DRAWIO_URL}
    ports:
      - "${DRAWIO_PORT}:8080"

    # swarm part
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${DRAWIO_NODE}"

volumes:
  plantuml_temp: