services:

  plantuml:

    # main
    image: ${PLANTUML_TAG}
    hostname: 'plantuml'
    environment:
      BASE_URL: "${PLANTUML_URL}"
      TZ:       "${TZ}"
    ports:
      - "${PLANTUML_PORT}:8080"
    volumes:
      - plantuml_temp:/tmp/jetty

    # swarm
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${PLANTUML_NODE}"

  draw-io:

    # main
    image: ${DRAWIO_TAG}
    hostname: 'drawio'
    environment:
      PUBLIC_DNS: ${DRAWIO_URL}
    ports:
      - "${DRAWIO_PORT}:8080"

    # swarm
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname == ${DRAWIO_NODE}"

# main
volumes:
  plantuml_temp: